### ISSUE TITLE
admin interface: impossible to create new ui_metadata

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#908]
we have an empty drop_down component for the name field in the ui_metadata editor.

how can it be filled?

**Comment by sbrunner** [comment]
Hello,

In the file `vars_<package>.yaml` you should add the `available_metadata`,  something like this:

```yaml
    admin_interface:
        ...
        # The list of available variable names for the `UI metadatas` form.
        available_metadata:
        - <a value>
        - <an other value>
```
